name: Run tests

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Doc support tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          bb: 'latest'

      - name: Check docs
        run: |
          cp API.md API.md.orig
          bb quickdoc
          diff API.md.orig API.md

