# adapted from https://github.com/anze3db/words-tui/blob/main/.github/workflows/publish.yml
name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    env:
      BB_BLENDER_TEST_HOME: "~/blender"
      BB_BLENDER_VERSION: "4.2"

    environment: release
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # github release upload

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build package
      run: poetry build && python scripts/bb_addon_create.py

    - name: Restore Blender from cache
      id: cache-blender
      uses: actions/cache/restore@v4
      with:
        path: ~/blender
        key: ${{ runner.os }}-blender-$BB_BLENDER_VERSION

    - name: Install Blender
      if: steps.cache-blender.outputs.cache-hit != 'true'
      run: |
        poetry run python scripts/blender_install.py $BB_BLENDER_VERSION

    - name: "Save Blender in cache"
      if: steps.cache-blender.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ~/blender
        key: ${{ steps.cache-blender.outputs.cache-primary-key }}

    - name: Build extension
      run: poetry run basilisp run scripts/bb_extension_create.lpy

    - name: Upload release artifacts
      run: gh release upload ${{ github.event.release.tag_name }} dist/*.{tar.gz,whl} out/nrepl_panel_addon*.py extension/*.zip
      env:
        GH_TOKEN: ${{ github.token }}
    # - name: Publish package distributions to PyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
